---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: appeng-devs
  title: AppEng - Petstore Developers
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: appeng-petstore
  title: AppEng - Petstore System
spec:
  owner: appeng-petstore-devs
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: appeng-petstore
  title: AppEng - Petstore Backend API
  description: |
    AppEng - This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about
    Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!
    You can now help us improve the API whether it's by making changes to the definition itself or to the code.
    That way, with time, we can improve the API in general, and expose some of the new features in OAS3.
  links:
    - title: Appeng-Petstore
      url: https://petstore3.swagger.io/
    - title: Appeng - Petstore API
      url: https://petstore3.swagger.io/api/v3/openapi.json
spec:
  type: openapi
  system: appeng-petstore
  owner: appeng-petstore-devs
  lifecycle: staging
  definition:
    $openapi: https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.0/petstore.yaml

